### ISSUE TITLE
Custom validator logic

### ISSUE THREAD

**Issue by flimzy** [invopop/validation#1]
We need to create our own validator to replace `github.com/go-ozzo/ozzo-validation`, which is not very well maintained, bigger than we need, and not very portable (doesn't work with GopherJS).

I'm opening this issue to discuss what types of validations we need, and hammer out a basic validation API.

**Comment by flimzy** [comment]
I don't think there's any way to copy ozzo's API, and retain compatibility with GopherJS.  The core of the problem is the way struct fields are referenced:

```golang
validation.ValidateStruct(&c, validation.Field(&c.Code, validation.Required))
```

Here we pass a pointer to `c.Code`.  The way ozzo handles this is by looping through all the fields of `c`, comparing the pointer address of each field with that of `&c.Code`.

In GopherJS, there are no pointer addresses (they all report as `0`), so this won't work.

The closest I can think of, in terms of API, is to change the calling convention to something like this:

```golang
validation.ValidateStruct(&c, validation.Field("Code", validation.Required))
```

That is to say: We pass the name of the field to validate, rather than a pointer to it.  GopherJS should be able to resolve this, as no pointers are involved.

It is a bit more error prone, because a typo won't be caught by the compiler.

**Comment by flimzy** [comment]
The other approach I can think of is just to do our validation more "naturally". I.e. something like:

```golang
func (t *Type) Validate() error {
    if t.Foo == nil {
        return errors.New("t.Foo must be set")
    }
}
```

This could be cleaned up a bit with some helper libraries, if we really want to, with something like:

```golang
func (t *Type) Validate() error {
    if e := validate.NotNil(t.Foo) { return e }
}
```

where `NotNil` (and related) are simple helpers (akin to an assert library... lol)

**Comment by samlown** [comment]
Oh, I see... that's probably a show-stopper then, as ideally you want the validation stuff to require as little code as possible. I have a feeling that GopherJS may have other road-blocks around the crypto stuff and may cause further confusion. Might be best to park this for a while and see what more use-cases of validation come up inside GOBL to have a more complete picture before investing more time in this. We can get by very well with WASM support for the time being!
